spring:
  security:
    user:
      password: Messi2025!
      name: Rufat
  config:
    activate:
      on-profile: "!test"
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        platform: org.hibernate.dialect.PostgresSQLDialect
